# site settings
title: facebook.jokeru.ro
email: fake@no.email
description: bucăți din viață
url: "https://facebook.jokeru.ro"
baseurl: ""

# build settings
markdown: kramdown
theme: jekyll-theme-architect
